### ISSUE TITLE
Uses wrong local IP address when multiple IP addresses are available

### ISSUE THREAD

**Issue by JJTech0130** [kaklakariada/portmapper#100]
I have WSA, so I have an IP address for that (virtual) network, as well as a regular one. Checking the "localhost" checkbox chooses one at random, even if it doens't match the UPNP router's subnet.

**Comment by JJTech0130** [comment]
It appears to pick the first one it finds, not randomly. Disabling and re-enabling the WSA network to make it not the first on temporarily fixes the problem.

**Comment by kaklakariada** [comment]
I am not sure how to solve this. If the IP address changes, I recommend to explicitly configure the correct IP instead of using the "localhost" checkbox.

**Comment by kaklakariada** [comment]
Closing as stale.
