### ISSUE TITLE
very bad 13:16:48.845 [main] ERROR org.chris.portmapper.PortMapperCli - Found no router 13:16:48.846 [main] ERROR org.chris.portmapper.PortMapperCli - No router found: exit

### ISSUE THREAD

**Issue by nturri1306** [kaklakariada/portmapper#102]
java -jar portmapper-2.2.1.jar -ip 192.168.168.107 -add -externalPort 7777 -internalPort 80 -protocol tcp

have always error

13:16:45.807 [main] INFO  o.f.cling.transport.spi.DatagramIO - Creating bound socket (for datagram input/output) on: /172.29.224.1
13:16:45.817 [main] INFO  org.fourthline.cling.UpnpServiceImpl - <<< UPnP service started successfully
13:16:45.818 [main] INFO  o.c.p.r.cling.ClingRouterFactory - Start searching PT3S for device type (UDADeviceTypeHeader) 'urn:schemas-upnp-org:device:InternetGatewayDevice:1'
13:16:45.824 [main] DEBUG o.c.p.r.cling.ClingRegistryListener - Waiting for PT3S until routers are found
13:16:48.845 [main] ERROR org.chris.portmapper.PortMapperCli - Found no router
13:16:48.846 [main] ERROR org.chris.portmapper.PortMapperCli - No router found: exit

**Comment by nturri1306** [comment]
i try

java -jar portmapper-2.2.1.jar -ip 192.168.168.107 -add -externalPort 7777 -internalPort 80 -protocol tcp -lib org.chris.portmapper.router.weupnp.WeUPnPRouterFactory

or

java -jar portmapper-2.2.1.jar -ip 192.168.168.107 -add -externalPort 7777 -internalPort 80 -protocol tcp  -lib org.chris.portmapper.router.sbbi.SBBIRouterFactory

but always errore

router.sbbi.SBBIRouterFactory
20:53:29.812 [main] INFO  org.chris.portmapper.PortMapperCli - Searching for routers...
20:53:29.812 [main] DEBUG o.c.p.router.sbbi.SBBIRouterFactory - System property 'portmapper.locationUrl' not defined: discover routers automatically.
20:53:35.953 [main] ERROR org.chris.portmapper.PortMapperCli - Found no router
20:53:35.953 [main] ERROR org.chris.portmapper.PortMapperCli - No router found: exit

**Comment by kaklakariada** [comment]
Sorry, I can't help you there, this is probably an issue with you router. Please check the troubleshooting section: https://github.com/kaklakariada/portmapper#router-not-found
