### ISSUE TITLE
Router Dissapeared

### ISSUE THREAD

**Issue by dejannufc** [kaklakariada/portmapper#105]
Hi, I have been using this to set ports up as I have a setup with a Router and a wireless access point. The Port Mapper used to find both routers with no problem, until today when it's randomly only been able to find my wireless access point and not the router. I'm not sure what has caused this, but it coincided with an IP address change as I had forgotten to set it to static.

**Comment by kaklakariada** [comment]
Hi @dejannufc,
which UPnP library do you use? Please check if a different library finds your routers.
If this does not help there is not much I can do to fix this.

**Comment by dejannufc** [comment]
Checked with each library. Thought there wouldn't be much you could do. Thank you for responding anyway
