### ISSUE TITLE
Port mappings reset after router restart

### ISSUE THREAD

**Issue by xNovite** [kaklakariada/portmapper#111]
Whenever my router restarts, all saved mappings reset. It's quite annoying having to re-add them, especially if you're running a server that has clients coming in and out.

Consider this as an 'enhancement'

**Comment by kaklakariada** [comment]
A workaround could be using the the command line to regularly update the port mappings as described [here](https://github.com/kaklakariada/portmapper#port-mappings-are-expiring).

**Comment by kaklakariada** [comment]
Closing as stale.
