### ISSUE TITLE
Keep Getting this error INFO  Got error response when fetching port mapping for entry number 12: '(IncomingActionResponseMessage) 500 Internal Server Error'. Stop getting more entries. INFO  Found 12 mappings

### ISSUE THREAD

**Issue by ColeFreeman72** [kaklakariada/portmapper#115]
I am Connected to the port1 of my router but it keep getting this error?

INFO  Got error response when fetching port mapping for entry number 12: '(IncomingActionResponseMessage) 500 Internal Server Error'. Stop getting more entries.

INFO  Found 12 mappings

DEBUG Connected to router, get IP of localhost from socket...
DEBUG Get IP of localhost
DEBUG Got internal router port -1
DEBUG Got invalid internal router port number -1
DEBUG Not connected to router or got invalid port number, can not use socket to determine the address of the localhost. If no address is found, please connect to the router.
DEBUG Got address DESKTOP-94CRJ5T/192.168.1.200 via InetAddress.getLocalHost().
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27015 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: TCP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27015 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27015 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: UDP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27015 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27036 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: UDP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27036 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27031 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: UDP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27031 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27032 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: UDP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27032 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27033 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: UDP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27033 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27034 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: UDP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27034 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27035 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: UDP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27035 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewRemoteHost:  (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewExternalPort: 27036 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewProtocol: UDP (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalPort: 27036 (expected datatype: ui2)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewInternalClient: 192.168.1.200 (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewEnabled: true (expected datatype: boolean)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewPortMappingDescription: Half-Life (expected datatype: string)
TRACE Action AddPortMapping: add arg value for (ActionArgument, IN) NewLeaseDuration: 0 (expected datatype: ui4)
INFO  9 port mapping added successfully
DEBUG Getting port mapping with entry number 0...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 0 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 1...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 1 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 2...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 2 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 3...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 3 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 4...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 4 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 5...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 5 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 6...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 6 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 7...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 7 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 8...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 8 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 9...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 9 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 10...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 10 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 11...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 11 (expected datatype: ui2)
DEBUG Getting port mapping with entry number 12...
TRACE Action GetGenericPortMappingEntry: add arg value for (ActionArgument, IN) NewPortMappingIndex: 12 (expected datatype: ui2)
ERROR Invocation (ActionInvocation) (Action, Arguments: 9) GetGenericPortMappingEntry failed with operation '500 Internal Server Error', body '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
<errorCode>713</errorCode>
<errorDescription>SpecifiedArrayIndexInvalid</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>
'

INFO  Got error response when fetching port mapping for entry number 12: '(IncomingActionResponseMessage) 500 Internal Server Error'. Stop getting more entries.

**Comment by kaklakariada** [comment]
This is a known issue with UPnP. Please ignore the error message, everything should work as expected. See https://github.com/kaklakariada/portmapper#error-when-fetching-port-mappings for details.
