### ISSUE TITLE
Does not work with Google Home routers.

### ISSUE THREAD

**Issue by AgitationSkeleton** [kaklakariada/portmapper#116]
(Using a QuakeWorld server to test, specifically NQuake.)

This is the only UPnP library that will actually successfully connect, the rest time out:
`routerFactoryClassName=org.chris.portmapper.router.weupnp.WeUPnPRouterFactory`

```
INFO  - model description = Wireless Router
INFO  Router info:
INFO  - device type = urn:schemas-upnp-org:device:WANConnectionDevice:2
INFO  - device type cif = urn:schemas-upnp-org:device:WANDevice:2
INFO  - friendly name = OnHub
INFO  - manufacturer = Google
```

However, when ports are mapped, they still cannot be seen from outside. 

![image](https://github.com/kaklakariada/portmapper/assets/21989910/923b3fd0-4bcf-48cd-8041-09e2daa38bd0)

With these ports mapped and the NQuake server definitely running, compared to another machine that has one on a forwarded port, it cannot be seen from the outside. GameTracker can't see it, Quakeservers.net can't see it, Canyouseeme can't see it etc.

**Comment by kaklakariada** [comment]
If I understand your problem, the port forwarding appears in the list but does not work. I am sorry, but it looks like this is an issue with the Google Home router. It might be that the router ignores the port forwardings. Please check the router's UPnP configuration and try to manually create a port mapping via the router's UI.

**Comment by kaklakariada** [comment]
Closing as stale.
