### ISSUE TITLE
Help for use it or install in on macOS pls

### ISSUE THREAD

**Issue by JosephFM96** [kaklakariada/portmapper#121]
have the folder and guess I successfully install gradlew or grade (as terminal says it founds that similar formula) and also run the command line script on the folder but when I type bradlew/bradle on terminal for run it or run the jar file doesn't recognize the command. So.. any help here or a video tutorial of steps to follow for correctly use it? Btw im stuck on the can't find router on the app

**Comment by kaklakariada** [comment]
Hi @JosephFM96 ,
Do you want to develop PortMapper or just use it? If you only want to use it, you can download file portmapper-2.2.3.jar  from the [release page](https://github.com/kaklakariada/portmapper/releases/tag/v2.2.3). Then run it with the following command:

```sh
java -jar portmapper-2.2.3.jar
```

It's not necessary to build it yourself with gradle.

Please follow the [troubleshooting guide](https://github.com/kaklakariada/portmapper#router-not-found) if your router is not found.

**Comment by kaklakariada** [comment]
Closing as stale.
