### ISSUE TITLE
doesn't open ports

### ISSUE THREAD

**Issue by THEKILERFRIEND** [kaklakariada/portmapper#124]
INFO  Searching for routers...
DEBUG System property 'portmapper.locationUrl' not defined: discover routers automatically.
INFO  Connected to router 'CH7465VF'
TRACE Updating addresses...
DEBUG Get internal IP address...
INFO  Got internal host name '192.168.0.1' for router.
DEBUG Get external IP address...
DEBUG Connection state changed to true
INFO  Got external IP address 0.0.0.0 for router.
TRACE Updating port mappings...
DEBUG Getting port mapping with entry number 0...
TRACE Got port mapping #0: UDP :1441 -> 192.168.0.115:1441 enabled ret
DEBUG Getting port mapping with entry number 1...
TRACE Got port mapping #1: TCP :1441 -> 192.168.0.115:1441 enabled ret
DEBUG Getting port mapping with entry number 2...
DEBUG Got no port mapping for entry number 2 (error code: 713, error description: SpecifiedArrayIndexInvalid). Stop getting more entries.
DEBUG Found 2 mappings, 0 mappings returned as null.
INFO  Found 2 mappings
TRACE done

It says mapping done but i checked it with port scanner while using port and while not using port and it wont work.

**Comment by THEKILERFRIEND** [comment]
![image](https://github.com/kaklakariada/portmapper/assets/32984678/504d6f1a-0d9d-437a-9d0c-878e901e1b4a)

**Comment by kaklakariada** [comment]
Sorry for the late response. Could you solve the issue in the meantime?

**Comment by kaklakariada** [comment]
I am closing this. If the problem still exists feel free to re-open this issue.
