### ISSUE TITLE
says no router detected but im connected to a router

### ISSUE THREAD

**Issue by ggMustaGD1** [kaklakariada/portmapper#125]
so i just started using it and when i say connect it says no router detected even though i am connected to one

**Comment by kaklakariada** [comment]
Hi @ggMustaGD1 ,

its possible that your router doesn't support UPnP or UPnP is deactivated in the settings. Please follow the [troubleshooting guide](https://github.com/kaklakariada/portmapper?tab=readme-ov-file#router-not-found).

**Comment by kaklakariada** [comment]
I am closing this. If the problem still exists feel free to re-open this issue.
