### ISSUE TITLE
Got null port mapping for index 0

### ISSUE THREAD

**Issue by caiknori** [kaklakariada/portmapper#127]
```
DEBUG Connected to router, get IP of localhost from socket...
DEBUG Get IP of localhost
DEBUG Got internal router port 5555
DEBUG Creating socket to router: 192.168.1.1:5555...
DEBUG Got address /192.168.1.5 from socket.
INFO  3 port mapping added successfully
DEBUG Getting port mapping 0...
DEBUG Entry 0 does not exist, stop getting more mappings
DEBUG Got null port mapping for index 0
INFO  Found 0 mappings
```

Using router AOT-4221SR

**Comment by kaklakariada** [comment]
Hi @caiknori ,
the log message `Got null port mapping for index 0` is normal when the router does not return a port mapping. Please try the steps in the [troubleshooting section](https://github.com/kaklakariada/portmapper?tab=readme-ov-file#adding-port-forwardings-not-possible).

**Comment by caiknori** [comment]
Sorry for not replying; but which steps exactly? Theres no clear steps relating to my Issue.

**Comment by kaklakariada** [comment]
You didn't specify your problem you have. From the log I assumed you wanted to create three mappings but they don't show up in Portmapper.

The link I sent shows possible ways to fix creating the mappings. 

When you exactly describe your problem, it's easier for me to help you solve it.

**Comment by kaklakariada** [comment]
I am closing this. If the problem still exists feel free to re-open this issue.
