### ISSUE TITLE
Unable to use preset

### ISSUE THREAD

**Issue by etpof** [kaklakariada/portmapper#13]
Recently downloaded PortMapper and it seems to be a convenient program, but I can't get it to work.

At the moment, I'm making an Unturned (video game) server for me and my friends to play on. I have the server files setup and can connect to it via localhost, but am having some problems port-forwarding with PortMapper.

I can start up PortMapper and connect to my router fine, so I'm assuming its UPnP compatible, but whenever I try to use a port preset, it never actually adds it to my port list. This is similar to when I attempt to remove a port. The console claims that the program is removing it, but the port never ends up being removed.

If anything else is needed (screenshots, log, etc.), I can provide that. Any help is appreciated!

-Thanks, 
ETPOF

**Comment by kaklakariada** [comment]
Hi etpof,
It looks like your router is silently ignoring updates sent by PortMapper. Maybe it has a setting that prevents modifications via UPnP?

Hope that helps,
Kaklakariada.
