### ISSUE TITLE
Error "A Java exception has occurred"

### ISSUE THREAD

**Issue by lemaximedu66** [kaklakariada/portmapper#135]
![image](https://github.com/user-attachments/assets/31a186b4-fbad-4630-87ad-503c4baaece7)
*very descriptive thx java lmao*

![image](https://github.com/user-attachments/assets/59eea696-57f9-4750-bc61-ad08479e4f62)

**Comment by kaklakariada** [comment]
Hi @lemaximedu66 ,

It looks like you are using an old version of Java. Please download a newer version, for example 21 from https://adoptium.net/temurin/releases/?package=jre and install it.

**Comment by kaklakariada** [comment]
If this does not work, please start PortMapper on the command line:

```sh
java -jar portmapper.jar
```

This should output a more helpful error message.

**Comment by lemaximedu66** [comment]
idk why but it works with the "java" command wtf

**Comment by lemaximedu66** [comment]
![image](https://github.com/user-attachments/assets/896ef1d1-bf22-4b90-b8c0-263174a484b6)

im confused

**Comment by lemaximedu66** [comment]
> Hi @lemaximedu66 ,
> 
> It looks like you are using an old version of Java. Please download a newer version, for example 21 from https://adoptium.net/temurin/releases/?package=jre and install it.

i updated it less than 1-2 months ago

**Comment by kaklakariada** [comment]
OK. It looks like your Windows uses two different Java versions: it uses Java 8 when double clicking the `.jar` file, but the `Path` environment variable points to `java` command from Java 19.

You could
1. Uninstall Java 8 and Java 19 and install Java 21 and try to double click again
2. Create a small `.bat` file containing the `java -jar` command und use that for starting PortMapper.

**Comment by lemaximedu66** [comment]
thats weird cuz when you go on java.com it makes you download the first version (the java 8 thing) and i think the other is called Java Developpment kit or something and it isn't offered on java.com and i also think minecraft won't run on jdk

**Comment by kaklakariada** [comment]
That's strange. Java 8 is deprecated since a long time and not supported any more. I recommend downloading from https://adoptium.net/temurin/releases/?package=jre&os=windows

**Comment by Usalabs** [comment]
I have the same problem, but the Java update says I have the most up to date version and as long as it says that, there's no way I'm fiddling about with download this, upload that, change this and that, the Java update says I'm running:-

Java (Oracle)
Version 8 Update 431 (Build 1.8.0_431-b10)

And running java -jar portmapper-2.2.4.jar is using the java runtime binary, and this is what I get:-

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/chris/portmapper/PortMapperStarter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

So how can the java file be compiled using a newer version when there's only one new version out and I have that already?  Therefore it should work with the version I have.

So I downloaded version 2.0.0, it works, but I can't use presets, when I create a preset and click 'Use', then click "Connect", nothing happens.

**Comment by kaklakariada** [comment]
Regarding the version check: I assume that your system checks for the latest update of Java 1.8.0. In your case this is update 431, which in fact is the latest update of 1.8.0. The automatic updater probably will not update to a later Java release like 11 or 17.

As far as I understand the only way for you to use the latest PortMapper version is to manually install Java 11, 17 or 21 from https://adoptium.net/temurin/releases/?package=jre&os=windows

If you don't want to modify your system, you can also download the JRE as a ZIP. You only need to unpack it into an arbitrary directory and start PortMapper using `<dir>\bin\java.exe`.

**Comment by lemaximedu66** [comment]
Forgot to close this (thanks Github notifications), I think it worked when I installed a more recent version of Java, will reopen if I have issues again
