### ISSUE TITLE
Prevent mappings from expiring.

### ISSUE THREAD

**Issue by ProjectInfinity** [kaklakariada/portmapper#14]
Would it be possible to add a feature to prevent a mapping from expiring as long as the application is open? It would be a really nice quality of life feature.

**Comment by kaklakariada** [comment]
Thanks for the suggestion! I will think about adding this feature. In the meantime you could use the command line interface of PortMapper to create a cron job that adds the port mapping every hour or so.

**Comment by ProjectInfinity** [comment]
Any updates on this? :)

**Comment by laflamee** [comment]
Any updates on this? I REALLY need this.

**Comment by kaklakariada** [comment]
Sorry, no update. As a workaround you can create a short shell script that invokes PortMapper every hour.

**Comment by laflamee** [comment]
Mind sharing the code for the shell script that opens portmapper and "presses" the use button to get the ports on?

**Comment by kaklakariada** [comment]
You can find examples via google:
* Windows: https://superuser.com/questions/66975/do-something-every-10-seconds-batch-file
* Unix: https://www.cyberciti.biz/faq/bash-infinite-loop/

**Comment by laflamee** [comment]
Trying to test it a bit and i got this error http://prntscr.com/ocolpf

**Comment by laflamee** [comment]
Update: now i got this http://prntscr.com/ocrjno

**Comment by laflamee** [comment]
I found out how to do it after installing latest jdk again, is there a command to just force the Presets instead of adding the ports over and over again?
:loop
cd E:\Documents\Port Mapper
java -jar "Port Mapper.jar" -add -externalPort 28020 -internalPort 28015 -protocol tcp
java -jar "Port Mapper.jar" -add -externalPort 28020 -internalPort 28015 -protocol udp
timeout /t 3600
goto loop

**Comment by laflamee** [comment]
Is there a way to use only one command line, eg: java -jar "Port Mapper.jar" -add -externalPort 28015 -internalPort 28015 -protocol tcp, -add -externalPort 28015 -internalPort 28015 -protocol udp WITHOUT typing java -jar 4 times? to make less cpu cycles

**Comment by laflamee** [comment]
Also how can i run the windows bat file invisibile? should i use an external software or there is a code for that?

**Comment by kaklakariada** [comment]
1. You can't specify more than one port on the command line.

2. For running the bat file as a service: https://lmgtfy.com/?q=run+batch+file+as+windows+service

**Comment by kaklakariada** [comment]
Added documentation how to avoid expiring port mappings: https://github.com/kaklakariada/portmapper#port-mappings-are-expiring
