### ISSUE TITLE
Port Status

### ISSUE THREAD

**Issue by luishts** [kaklakariada/portmapper#15]
Hello,

I'm using your software to open some ports using UPnP api but take a look at the below scenarious:

INFO  Adding port mapping luisinho
INFO  Adding port mapping TCP 192.168.0.100:31055 -> 192.168.0.101:31055 enabled luisinho
INFO  Adding port mapping luisinho
INFO  Adding port mapping UDP 192.168.0.100:31055 -> 192.168.0.101:31055 enabled luisinho
INFO  2 port mapping added successfully

Above port mapping added to my router:

3   luisinho    31055   TCP 31055   192.168.0.101   enable
4   luisinho    31055   UDP 31055   192.168.0.101   enable

But when I try to connect to my public ip + port 31055 I receive a timeout.

I'm using this site (http://www.ipfingerprints.com/portscan.php) to check port status and port 31055 is marked as:

31055/tcp filtered unknown

But when I check skype upnp at my router:

2   Skype TCP at 192.168.0.101:3105 31051   TCP 31051   192.168.0.101   enable

And check port status at site:

31051/tcp open          unknown

Do you know why I'm getting port status filtered even if the port is added at upnp router list ?

**Comment by kaklakariada** [comment]
Can you please check, if the port forwardings are displayed in the user interface of your router? And can you check if the server is running on the specified port?
