### ISSUE TITLE
Port as filtered

### ISSUE THREAD

**Issue by tpiva** [kaklakariada/portmapper#16]
Hello,

I'm using your software to open port using UPnP, but the port shows as "filtered". I tried to use all libs include on PortMapper, however with the same result. I site below to scan port and its status: http://www.ipfingerprints.com/portscan.php . So, do you know why this status happens?

A couple of things: I tried to add exception on firewall, disable it and analysis with Wireshark what's going on.

So, If you have any clue I'll apreciate.

Thanks and best regards,
Thiago

**Comment by kaklakariada** [comment]
Hi Thiago,
sorry for the delayed reply.
One reason could be that your router does not apply port forwardings defined via UPnP and just reports them. Can you please try to setup the port forwarding via the router's user interface?
