### ISSUE TITLE
Can't find router

### ISSUE THREAD

**Issue by TheRActivator** [kaklakariada/portmapper#20]
WARN  unspecified resource Application.vendorId using UnknownApplicationVendor
INFO  Using default configuration directory 'C:\Users\Arie\AppData\Roaming\UnknownApplicationVendor\PortMapper'.
DEBUG Loading settings from file settings.xml
DEBUG Settings were not loaded from file settings.xml: create new settings
DEBUG Open Settings dialog
DEBUG Create settings dialog
DEBUG Use entity encoding is true
INFO  Creating router factory for class org.chris.portmapper.router.cling.ClingRouterFactory
DEBUG Router factory Cling lib created
INFO  Searching for routers...
DEBUG System property 'portmapper.locationUrl' not defined: discover routers automatically.
INFO  >>> Starting UPnP service...
INFO  Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
INFO  Creating Router: org.fourthline.cling.transport.RouterImpl
WARN  Network interface may not be multicast capable: Microsoft Teredo Tunneling Adapter
INFO  Creating wildcard socket (for receiving multicast datagrams) on port: 1900
INFO  Joining multicast group: /239.255.255.250:1900 on network interface: LogMeIn Hamachi Virtual Ethernet Adapter
INFO  Creating wildcard socket (for receiving multicast datagrams) on port: 1900
INFO  Joining multicast group: /239.255.255.250:1900 on network interface: Intel(R) Dual Band Wireless-AC 3160
INFO  Creating wildcard socket (for receiving multicast datagrams) on port: 1900
INFO  Joining multicast group: /239.255.255.250:1900 on network interface: ASIX AX88772A USB2.0 to Fast Ethernet Adapter
INFO  Created server (for receiving TCP streams) on: /25.79.28.69:58335
INFO  Creating bound socket (for datagram input/output) on: /25.79.28.69
INFO  Created server (for receiving TCP streams) on: /192.168.23.9:58338
INFO  Creating bound socket (for datagram input/output) on: /192.168.23.9
INFO  Created server (for receiving TCP streams) on: /192.168.23.28:58341
INFO  Creating bound socket (for datagram input/output) on: /192.168.23.28
INFO  <<< UPnP service started successfully
DEBUG Start searching using upnp service
DEBUG Did not find a service after 5 seconds
WARN  Could not connect to router: Did not find a router
org.chris.portmapper.router.RouterException: Did not find a router
	at org.chris.portmapper.PortMapperApp.connectRouter(PortMapperApp.java:220)
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:456)
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:444)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
WARN  Could not connect to router: Did not find a router

I tried every UPnP library, but it can't find my router!

**Comment by kaklakariada** [comment]
I am sorry, there is not much I can do here. The only thing that comes to my mind is that UPnP is disabled in your router. Please check if you can enable it via the user interface.

**Comment by TheRActivator** [comment]
Thing is, I'm trying to use portmapper _because_ I don't have access to the user interface.

**Comment by kaklakariada** [comment]
Sorry, then I can't help you here.
