### ISSUE TITLE
4 minutes for "Shutdown registry"

### ISSUE THREAD

**Issue by nikagl** [kaklakariada/portmapper#22]
Hi all,

I am running a script that calls "portmapper-2.0.0.jar" to map my ports if they are not available anymore. 

Great so far! I am running it on Windows 2012 R2 and use Java version 1.8.0_91:
`java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode)`

For some reason it sometimes takes very long to exit the jar after "Shutdown registry":
`14:05:07.027 [main] DEBUG o.c.p.router.cling.ClingRouter - Shutdown registry
Fri 11/25/2016 14:08:06.61 Done`

The commandline I use is:
`java -jar portmapper-2.0.0.jar -list -lib org.chris.portmapper.router.cling.ClingRouterFactory`

Note that I tried WeUPnPRouterFactory and SBBIRouterFactory too, but it looks like my router can only be discovered using ClingRouterFactory... When using WeUPnPRouterFactory after specifying the locationUrl (with "-Dportmapper.locationUrl=")...

Regards,

Nika.

**Comment by kaklakariada** [comment]
Thanks for reporting this issue! This needs to be fixed in the Cling library, please report this at https://github.com/4thline/cling. PortMapper uses the latest version 2.1.1 of Cling.
