### ISSUE TITLE
Can't select router library via CLI

### ISSUE THREAD

**Issue by ChaoticWyrme** [kaklakariada/portmapper#23]
The docs are not clear what to use as input for the -lib switch on the CLI. I have tried the full class name and various abbreviations. Please help.

**Comment by gustavoghd** [comment]
Same here.
It works perfectly on my Windows 7 machine, but I need it to run on my Raspberry(CRONtab). On the Raspberry it can't find my router like it does on the Windows 7 machine. 
I would like to change the library using the command line but I don't know how.

**Comment by gouldner** [comment]
I am having same issue on Mac 10.12.6.  I tried 
java -jar portmapper-2.0.0.jar -lib org.chris.portmapper.router.weupnp.WeUPnPRouterFactory
and
java -jar portmapper-2.0.0.jar -lib weupnp
but it still keeps using the default ClingRouterFactory

So either I am passing the -lib options incorrectly (readme could be improved) or this option isn't working.

**Comment by bfpa40** [comment]
I am also trying to use the CLI to call out a different UPnP Library and cannot get it to change. Does anyone have a resolution to this yet?

**Comment by kaklakariada** [comment]
What is the command you tried and what was the output?
