### ISSUE TITLE
Umlaute broken

### ISSUE THREAD

**Issue by Wolvan** [kaklakariada/portmapper#25]
Due to my Windows being set to german, the application automatically loads a german text set. The Umlaute are broken on 2.0.0 but they are working fine on 2.0.0-alpha-3.

In addition, could there be an option to override the language compared to what's being automatically loaded by the tool?

![image](https://cloud.githubusercontent.com/assets/1437010/26533594/4d9a36a8-441b-11e7-85bb-d3cf3351ad64.png)
![image](https://cloud.githubusercontent.com/assets/1437010/26533596/54084bf6-441b-11e7-9a07-47d6676dac63.png)

**Comment by kaklakariada** [comment]
I am working on fixing the umlaut problem. In the meantime you can manually select English:

    java -Duser.language=en -jar portmapper.jar

also see https://github.com/kaklakariada/portmapper/#select-language

**Comment by kaklakariada** [comment]
Should be fixed in the current version. Please re-test.

**Comment by Wolvan** [comment]
The issue is fixed in 2.1.1, closing this issue
