### ISSUE TITLE
Port Forwarding Not working. 

### ISSUE THREAD

**Issue by thatscot** [kaklakariada/portmapper#27]
Hello, 

In the port mapping window it says upd and tcp are both port forwarded to port 80. But when i use any online port forwarding tool they are closed. There are a few errors been thrown in the output box and my internal ip address isn't appearing on the left. 

```
 WARN  Device descriptor retrieval failed: http://192.168.1.161:49153/description0.xml, 401 Unauthorized
INFO  Saved preset 'Apache'.
INFO  2 port mapping added successfully
WARN  Device descriptor retrieval failed: http://192.168.1.161:49153/description1.xml, 401 Unauthorized
INFO  Got error response when fetching port mapping for entry number 91: '(IncomingActionResponseMessage) 500 Internal Server Error'. Stop getting more entries.
INFO  Found 91 mappings

```

The first warning is logged out frequently and fills pretty much the whole log. You can see it appear twice in that short time. Could you let me know if there is something I am doing wrong? Thank you

**Comment by kaklakariada** [comment]
Hi @thatscot error code 401 means that you need to authenticate with your router to make changes. PortMapper does not support this. Maybe you can switch this off in the web interface of your device?
