### ISSUE TITLE
Getting the message "Could not connect to router: could not find a router"

### ISSUE THREAD

**Issue by yanzae** [kaklakariada/portmapper#28]
I am trying to connect my router to Portmapper and it is unable to connect. I have heard that this might be due to the application being blocked in the Windows firewall but I did not get any such message. How can I figure out the root of the problem?

EDIT: Look at https://pastebin.com/gFRuW94p if you want to see the log messages, I put them there in case anyone wants to see them

**Comment by kaklakariada** [comment]
Hi @yanzae on my machine it works with default settings for the windows 10 firewall. You could try to
* Use a different UPnP library in the settings
* The log contains warning `Network interface may not be multicast capable: Teredo Tunneling Pseudo-Interface`. You could try to temporary disable this network interface
* Check if UPnP is activated in your router's settings

**Comment by yanzae** [comment]
I changed the UPnP library and that worked. Thanks!

**Comment by kaklakariada** [comment]
Great, thanks for the feedback!
I added a feedback section to the readme: https://github.com/kaklakariada/portmapper#troubleshooting
