### ISSUE TITLE
Cannot connect to miniupnpd using CLING or SBBI due to IGD version mismatch

### ISSUE THREAD

**Issue by nyetwurk** [kaklakariada/portmapper#29]
CLING reports:

DEBUG Found service of wrong type urn:schemas-upnp-org:device:InternetGatewayDevice:2, expected urn:schemas-upnp-org:device:InternetGatewayDevice:1.

SBBI provides no useful information

WeUPnP actually works.

See also

https://github.com/miniupnp/miniupnp/issues/277#issuecomment-362885613

**Comment by miniupnp** [comment]
Please note that according to UPnP Device Architecture v1.1 :

> 1.3.2 [...] **Updated versions of device and service types
> are REQUIRED to be full backward compatible with
> previous versions.** Devices MUST respond to M-SEARCH
> requests for any supported version. For example, if a
> device implements “urn:schemas-upnporg:service:xyz:2”,
> it MUST respond to search requests for both that type
> and “urn:schemas-upnp-org:service:xyz:1”. The response
> MUST specify the same version as was contained in the
> search request. [...]

**Comment by nyetwurk** [comment]
It seems as (most of?) these clients are *all* broken. Miniupnpd does respond with :1 if the search includes :1, it is only that NOTIFY shows :2, and that is what the clients are basing their decisions on.
