### ISSUE TITLE
When I Moved The .jar File The Text Got Messed Up

### ISSUE THREAD

**Issue by PiggyWiggles** [kaklakariada/portmapper#31]
I'm Not a Programmer So I Don't Know How To Fix This.
![port mapper](https://user-images.githubusercontent.com/36652836/36405888-0e656106-15c1-11e8-8a5d-1cf6cd621473.PNG)

**Comment by kaklakariada** [comment]
This is strange. Maybe the jar was modified. Please try to download the jar again.

**Comment by PiggyWiggles** [comment]
I have many times it stays the same.

**Comment by kaklakariada** [comment]
Please try to explicitly set the language to English (`en`) as described here: https://github.com/kaklakariada/portmapper#select-language
What operating system do you use?
