### ISSUE TITLE
PortMapper 2.0.0 "No Router Found"

### ISSUE THREAD

**Issue by bfpa40** [kaklakariada/portmapper#34]
First off let me thank you for an excellent program, I am using it (Version 2.0.0) successfully on a Ubuntu 17.10 I have copied it over to a RaspberryPi so I can have a low power option to remapping my ports while away from the house. While I can get 2.0.0 to run on the Pi it returns the following:

11:35:42.928 [main] INFO  org.chris.portmapper.PortMapperCli - Creating router factory for class org.chris.portmapper.router.cling.ClingRouterFactory
11:35:43.041 [main] DEBUG org.chris.portmapper.PortMapperCli - Creating a new instance of the router factory class class org.chris.portmapper.router.cling.ClingRouterFactory
11:35:43.531 [main] INFO  org.chris.portmapper.PortMapperCli - Searching for routers...
11:35:43.534 [main] DEBUG o.c.p.r.cling.ClingRouterFactory - System property 'portmapper.locationUrl' not defined: discover routers automatically.
11:35:44.108 [main] INFO  org.fourthline.cling.UpnpServiceImpl - >>> Starting UPnP service...
11:35:44.112 [main] INFO  org.fourthline.cling.UpnpServiceImpl - Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
11:35:44.385 [main] INFO  o.fourthline.cling.transport.Router - Creating Router: org.fourthline.cling.transport.RouterImpl
11:35:44.536 [main] INFO  o.f.c.t.spi.MulticastReceiver - Creating wildcard socket (for receiving multicast datagrams) on port: 1900
11:35:44.586 [main] INFO  o.f.c.t.spi.MulticastReceiver - Joining multicast group: /239.255.255.250:1900 on network interface: eth0
11:35:44.915 [main] INFO  o.f.cling.transport.spi.StreamServer - Created server (for receiving TCP streams) on: /172.16.42.8:36521
11:35:44.978 [main] INFO  o.f.cling.transport.spi.DatagramIO - Creating bound socket (for datagram input/output) on: /172.16.42.8
11:35:45.092 [main] INFO  org.fourthline.cling.UpnpServiceImpl - <<< UPnP service started successfully
11:35:45.102 [main] DEBUG o.c.p.r.cling.ClingRouterFactory - Start searching using upnp service
11:35:49.963 [cling-42] WARN  o.f.c.p.RetrieveRemoteDescriptors - Device descriptor retrieval failed, no response: http://172.16.42.2:1990/WFADevice.xml
11:35:50.361 [main] DEBUG o.c.p.r.cling.ClingRouterFactory - Did not find a service after 5 seconds
11:35:50.365 [main] ERROR org.chris.portmapper.PortMapperCli - Found no router
11:35:50.390 [main] ERROR org.chris.portmapper.PortMapperCli - No router found: exit

I see up at the top it reflects "11:35:43.534 [main] DEBUG o.c.p.r.cling.ClingRouterFactory - System property 'portmapper.locationUrl' not defined: discover routers automatically." might this be the cause? If so is there a file somewhere to modift/add the values for my Routers IP?

-Brian-

**Comment by kaklakariada** [comment]
I guess this is some kind of network problem. You can try the following:
* use a different library on your raspi with option `-lib <name>`. See [available libraries](https://github.com/kaklakariada/portmapper#upnp-libraries)
* Specify option location url. You can get it from the info output on your ubuntu machine: `java "-Dportmapper.locationUrl=<url>" -jar portmapper.jar ...`
