### ISSUE TITLE
Cant add port 3074

### ISSUE THREAD

**Issue by MisterX2003** [kaklakariada/portmapper#35]
sometimes this happens with other ports too... it will just NOT add no matter what. might conflict with the portmapper ports but thats stupid. 3074 is actually CoD WaW's port so it sucks ass. Please help

**Comment by kaklakariada** [comment]
Do other ports *sometimes* work or does port forwarding in general not work?
Have you tried the [troublshooting hints](https://github.com/kaklakariada/portmapper#troubleshooting)?

**Comment by MisterX2003** [comment]
Portforwarding does work in general but sometimes a port just wont forward and this is it. 3074 just refuses to be forwarded, and its not like another device is using that port or its already forwarded, I just cant forward it.

**Comment by kaklakariada** [comment]
This is strange. Maybe this is an issue with your router?
I am not an expert with the UPnP protocol as I just use the libraries as is.

**Comment by MisterX2003** [comment]
no UPnP is definitely enabled, it has worked countless times.
