### ISSUE TITLE
PortMapper 2.1.1 "No Router Found"

### ISSUE THREAD

**Issue by luckeydogg** [kaklakariada/portmapper#37]
I have UnNp Enabled & when I hit "Connect" I get the final message as:

WARN  Could not connect to router: Did not find a router

I do have a static ip set as 192.168.0.150.  Could that be an issue?

**Comment by kaklakariada** [comment]
Static IPs should not be a problem. You can try to use a different UPNP library and follow the [troubleshooting guide](https://github.com/kaklakariada/portmapper#troubleshooting).
