### ISSUE TITLE
Can't find router due to an error with a chromecast on the network

### ISSUE THREAD

**Issue by VenomiXeD** [kaklakariada/portmapper#41]
I have issues connecting to the router. It worked fine from the beginning. But things has been being a problem. Now when I try to connect to the router using the tool. It just can't do it. And returns "No router found". But as far as I know. I find the output:
`Found service of wrong type urn:schemas-wifialliance-org:device:WFADevice:1, expected urn:schemas-upnp-org:device:InternetGatewayDevice:1` and under. I found a link to this result returned from a Google chromecast dongle. Apparently

`<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.166:8008</URLBase>
<device>
<deviceType>urn:dial-multiscreen-org:device:dial:1</deviceType>
<friendlyName>Family Room TV</friendlyName>
<manufacturer>Google Inc.</manufacturer>
<modelName>Eureka Dongle</modelName>
<UDN>uuid:b7ed2f62-c261-61ea-750a-b95bc2160999</UDN>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>98</width>
<height>55</height>
<depth>32</depth>
<url>/setup/icon.png</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:dial-multiscreen-org:service:dial:1</serviceType>
<serviceId>urn:dial-multiscreen-org:serviceId:dial</serviceId>
<controlURL>/ssdp/notfound</controlURL>
<eventSubURL>/ssdp/notfound</eventSubURL>
<SCPDURL>/ssdp/notfound</SCPDURL>
</service>
</serviceList>
</device>
</root>`

Which I believe is a chromecast broadcast or like device description. 
Then I also found: `WARN  Service descriptor retrieval failed: http://192.168.1.166:8008/ssdp/notfound, 404 Not Found`

It's obviously weird because it has happened twice. After a month it worked again but soon after like 5 minutes it broke again.

**Comment by kaklakariada** [comment]
Thanks for reporting this! I tried to fix this but am not sure if it helped. Please try it again with this version: [portmapper-2.3.0-SNAPSHOT.jar.zip](https://github.com/kaklakariada/portmapper/files/3100213/portmapper-2.3.0-SNAPSHOT.jar.zip)
