### ISSUE TITLE
Support for multiple routers in LAN

### ISSUE THREAD

**Issue by elmimmo** [kaklakariada/portmapper#43]
What if the LAN has several routers with UPnP enabled? PortMapper connects to the first one it sees. It would be nice if there was a dropdown of sorts to choose among all detected.

**Comment by kaklakariada** [comment]
PortMapper supports multiple routers with SBBI and WeUPNP libraries.
When multiple routers are found after connecting, PortMapper shows a dialog where you can select one of the available devices.

**Comment by kaklakariada** [comment]
I added multiple router support to Cling. Please try it again with this version: [portmapper-2.3.0-SNAPSHOT.jar.zip](https://github.com/kaklakariada/portmapper/files/3100213/portmapper-2.3.0-SNAPSHOT.jar.zip)
