### ISSUE TITLE
Wrong XML namespace

### ISSUE THREAD

**Issue by gdevacc12** [kaklakariada/portmapper#44]
I tried each Library to connect to my router but get various errors, e.g. when trying to connect with Cling this error is logged:

18:01:19.075 [cling-5] WARN o.f.c.b.xml.DeviceDescriptorBinder - Wrong XML namespace declared on root element: urn:dslforum-org:device-1-0

Any clues on what to try next?

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

portmapper-2.2.0.jar

**Comment by kaklakariada** [comment]
I am sorry but I can't help you here. Your router seems to be not compatible to the UPnP standard.
