### ISSUE TITLE
Can't get anything to show under the port mappings table even when gateway is found.

### ISSUE THREAD

**Issue by Syniko** [kaklakariada/portmapper#46]
**Using Portmapper 2.2.0**
**Results with Cling**: https://pastebin.com/wnyNPQBp
**Results with SBBIRouterFactory**: https://pastebin.com/EecDPdZx
**Results with WeUPnPRouter**: https://pastebin.com/CKK6mtWq

**Router**: Nighthawk X6 R8000 (firmware is up-to-date at the time of posting)
**Network Card**: Asus PCE-AC56 (have tested this with both the drivers on Asus's website and the plug-and-play Windows drivers)

I've linked a few images to show my java version, and to show that I've enabled UPnP on my router and that it has existing entries in the portmap table.

Also side note, apparently when I try to use a preset it'll sometimes send a port to the portmap table, but if I want it to send the same port both as TCP and UDP in the same preset, it'll only send the TCP one to the portmap table.

**Images**:

![firefox_XuleqAaUoT](https://user-images.githubusercontent.com/4535248/70096747-cbe25500-15f5-11ea-899f-c2134d313443.png)

![cmd_b2pmjcehds](https://user-images.githubusercontent.com/4535248/70096765-dc92cb00-15f5-11ea-9954-4bf64d599df0.png)

![javaw_CvAhQndGBl](https://user-images.githubusercontent.com/4535248/70096837-021fd480-15f6-11ea-9209-cab8bfa714cb.png)

![javaw_iGi8LBHxCL](https://user-images.githubusercontent.com/4535248/70097270-f7197400-15f6-11ea-8b24-ac0e29452978.png)

**Comment by kaklakariada** [comment]
Thank you for your detailed bug report!
I am sorry but I can't help you here. I only use third party UPnP libraries in PortMapper. If these libraries don't work with your router you can only ask the maintainers of these libraries to fix this. Then I can include the new version of the library in PortMapper.
If you know another library that provides better support for your router I am happy to include this.
