### ISSUE TITLE
WARN Could not connect to router: Did not find a router

### ISSUE THREAD

**Issue by Yasuussan** [kaklakariada/portmapper#47]
What does this mean, and how do I fix this.

INFO  Searching for routers...
INFO  Found more than one router (count: 2): ask user.
INFO  Found 3 mappings
INFO  Saved preset 'TF2 Server'.
INFO  Creating router factory for class org.chris.portmapper.router.cling.ClingRouterFactory
INFO  Searching for routers...
INFO  >>> Starting UPnP service...
INFO  Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
INFO  Creating Router: org.fourthline.cling.transport.RouterImpl
INFO  Creating wildcard socket (for receiving multicast datagrams) on port: 1900
INFO  Joining multicast group: /239.255.255.250:1900 on network interface: Realtek PCIe GBE Family Controller
INFO  Created server (for receiving TCP streams) on: /192.168.0.150:58698
INFO  Creating bound socket (for datagram input/output) on: /192.168.0.150
INFO  <<< UPnP service started successfully
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not hydrate device or its services from descriptor: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:9634dbfd-8d60-42d6-896c-795595999b83, Descriptor: http://192.168.0.23:1082/, Root: true
WARN  Cause was: org.fourthline.cling.model.types.InvalidValueException: Can't parse device type string (namespace/type/version): urn:dial-multiscreen-org:service:dial:1
WARN  Could not connect to router: Did not find a router
org.chris.portmapper.router.RouterException: Did not find a router
	at org.chris.portmapper.PortMapperApp.connectRouter(PortMapperApp.java:220)
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:456)
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:444)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
WARN  Could not connect to router: Did not find a router

I have no experience with java at all, thats why im asking.

**Comment by kaklakariada** [comment]
It looks like the Cling UPnP library is not able to parse the device descriptor of your router. You could try the following:
* Use a different UPnP library in Portmapper
* Disable and re-enable UPnP in your router. This worked in a similar case: https://sourceforge.net/p/upnp-portmapper/bugs/62/
