### ISSUE TITLE
Scrambled characters 

### ISSUE THREAD

**Issue by BKCake** [kaklakariada/portmapper#49]
![PortMapper](https://user-images.githubusercontent.com/61220345/74804154-5a739200-531a-11ea-9e49-adad2d93acab.PNG)
This happened when I open up, prob related to UTF-8 and GBK
Since I am not very experienced in these stuff, I'm just gonna leave it here :)

My thoughts: The jar is prob wrote in UTF-8 but when I start it, it decode itself with GBK since somehow it think I use GBK

**Comment by kaklakariada** [comment]
Which locale do you use for your computer? Portmapper is also translated to Chinese. Maybe the encoding for Chinese is broken. Please try to start Portmapper in English by starting it on the command line:

```bash
java -Duser.language=en -jar portmapper.jar
```

**Comment by 1970633640** [comment]
@kaklakariada I use windows 10 in simplified Chinese and same problem happened. That command line to force start in English works. In my experience, Windows + Chinese is a disaster in command line or binary environment. There are GBK, Unicode, ANSI and UTF-8 messing with each other lol.
