### ISSUE TITLE
Can't update ports

### ISSUE THREAD

**Issue by samuelbarata** [kaklakariada/portmapper#50]
I have changed the configurations and only one of them can find my router
I can see all the ports but I'm unable to delete any of the existing or add new ones although the app says that the ports have been added/removed successfully

```
INFO  Router info:
INFO  - device type = urn:schemas-upnp-org:device:WANConnectionDevice:1
INFO  - device type cif = urn:schemas-upnp-org:device:WANDevice:1
INFO  - friendly name = NOS CPE Device
INFO  - location = http://192.168.1.1:2555/upnp/InternetGatewayDevice:1/desc.xml
INFO  - manufacturer = Cisco RG Israel
INFO  - model description = NOS CPE Device
```

**Comment by kaklakariada** [comment]
Looks like your router does not allow modifying port mappings. Maybe there is a setting in your router where you can allow modifications via UPnP.
