### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by n3tis** [kaklakariada/portmapper#52]
hi I opened this in commandline and I also installed two Javas nothing works, JavaSetup8u241.exe and jre-8u241-windows-x64 but it didn't work here's the log

please help me

Error: A JNI error has occurred, please check your installation and try again                 Exception in thread "main" java.lang.UnsupportedClassVersionError: org/chris/portmapper/PortMapperStarter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0               at java.lang.ClassLoader.defineClass1(Native Method)                                          at java.lang.ClassLoader.defineClass(Unknown Source)                                          at java.security.SecureClassLoader.defineClass(Unknown Source)                                at java.net.URLClassLoader.defineClass(Unknown Source)                                        at java.net.URLClassLoader.access$100(Unknown Source)                                         at java.net.URLClassLoader$1.run(Unknown Source)                                              at java.net.URLClassLoader$1.run(Unknown Source)                                              at java.security.AccessController.doPrivileged(Native Method)                                 at java.net.URLClassLoader.findClass(Unknown Source)                                          at java.lang.ClassLoader.loadClass(Unknown Source)                                            at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)                                 at java.lang.ClassLoader.loadClass(Unknown Source)                                            at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by kaklakariada** [comment]
You need Java 11 for running PortMapper. See
* https://github.com/kaklakariada/portmapper#portmapper-fails-to-start
* https://github.com/kaklakariada/portmapper#install_java
