### ISSUE TITLE
When would it be expected to get the next version update?

### ISSUE THREAD

**Issue by brunoais** [kaklakariada/portmapper#56]
When would it be expected to get the next version update?
For organizational purposes, not to try to hurry.

**Comment by kaklakariada** [comment]
Sorry, you are waiting for a release containing #54 ?
I will try to publish a release this weekend.

**Comment by brunoais** [comment]
Basically, yes.... And also other small improvements.

Thank you!

**Comment by kaklakariada** [comment]
I just published v2.2.1. You can download it from https://sourceforge.net/projects/upnp-portmapper/files/v2.2.1/

**Comment by brunoais** [comment]
Awesome! Thanks!
