### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by zyzkevin** [kaklakariada/portmapper#58]
![image](https://user-images.githubusercontent.com/52997677/90952037-cfbf4b80-e492-11ea-8642-8f9b80fadb82.png)
My settings (locale) are currently US Eng; however, the program isn't displaying the right characters.

**Comment by kaiwu-astro** [comment]
Dear developer, I have the same problem. I tried

`java -Duser.language=en -jar portmapper.jar`

and it gives

```
Error: Could not find or load main class .language=en
Cause : java.lang.ClassNotFoundException: /language=en
```

If I use language=de and it gives the same error (with .language=de)

I am running the program on Windows 10 with 

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

**Comment by kaklakariada** [comment]
Is it possible that there is a whitespace or hidden special character before the `.` in your command, e.g.
```
$ java -Duser .language=en -jar build/libs/portmapper-2.2.1-all.jar
Error: Could not find or load main class .language=en
Caused by: java.lang.ClassNotFoundException: /language=en
```
This is the only way I could explain the error message you get.

**Comment by kaiwu-astro** [comment]
Thank you for your quick reply.

I just comfirmed that there is no special character by typing the whole cmmand line again.

But I just solved this problem. I used to type the command in powershell, which always gives the error. I switch to cmd, and everything works fine. (stupid powershell)

**Comment by kaklakariada** [comment]
You are right. The problem only occurs using Powershell. I used bash before.
I will update the documentation.
