### ISSUE TITLE
Portmapper 2.2.1 cannot connect from external ip

### ISSUE THREAD

**Issue by JSJBDEV** [kaklakariada/portmapper#59]
There is a chance here I might not quite understand what I'm doing so bear with me.

I am running a Minecraft Server on Lubuntu (20.04 LTS) and have been trying to set up the portmapper such that I can access the server from my external ip on the port 25565 however whilst the mapping says it has been created and appears to work, I am unable to use the external IP address to connect to the server and thus cannot connect on another WiFi

I am use to using a Windows program called UPNPwizard and know it works and allows connections to the external IP over the internet and I know it works from this network 

Am I missing a library , have I don't something wrong, have I missinterpreted what this program is for or is this a bug?

Thank you for reading, any help is appreciated!

**Comment by kaklakariada** [comment]
Can you please try the following:

Create the port forwarding manually using your routers web interface and check if this works. This makes sure that port forwarding works.

**Comment by JSJBDEV** [comment]
Since that message I have subsequently done that manually and can confirm it is reachable from the internet, however I also tried using upnp wizard (the Windows program) to see if this was the case there and found this to be true which potentially means it's not your problem, but Minecraft might use a different system from hosting Lan words to hosting the default 25565 port, you might want to look into it but I have a feeling at this point it is MC side, but thank you for your response all the same!

**Comment by kaklakariada** [comment]
You are welcome, thanks for your feedback :-)
