### ISSUE TITLE
Router still not found (different router, DHL instead of UVerse)

### ISSUE THREAD

**Issue by JohnReedLOL** [kaklakariada/portmapper#6]
INFO  Using default configuration directory '/home/johnmichaelreed/.PortMapper'.
DEBUG Loading settings from file settings.xml
DEBUG Got settings [Settings: presets=[Dummy], useEntityEncoding=true, logLevel=ALL, routerFactoryClassName=org.chris.portmapper.router.cling.ClingRouterFactory]
TRACE Connecting to router...
INFO  Creating router factory for class org.chris.portmapper.router.cling.ClingRouterFactory
DEBUG Creating a new instance of the router factory class class org.chris.portmapper.router.cling.ClingRouterFactory
DEBUG Router factory created
INFO  Searching for routers...
DEBUG System property portmapper.locationUrl not defined: discover routers automatically.
INFO  >>> Starting UPnP service...
INFO  Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
INFO  Creating Router: org.fourthline.cling.transport.RouterImpl
INFO  Creating wildcard socket (for receiving multicast datagrams) on port: 1900
INFO  Joining multicast group: /239.255.255.250:1900 on network interface: wlan0
INFO  Created server (for receiving TCP streams) on: /192.168.10.104:60657
INFO  Creating bound socket (for datagram input/output) on: /192.168.10.104
INFO  <<< UPnP service started successfully
DEBUG Start searching using upnp service
DEBUG Did not find a service after 5 seconds
WARN  Could not connect to router: Did not find a router
org.chris.portmapper.router.RouterException: Did not find a router
	at org.chris.portmapper.PortMapperApp.connectRouter(PortMapperApp.java:207) ~[portmapper-master-2.0.0-alpha2.jar:na]
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:439) ~[portmapper-master-2.0.0-alpha2.jar:na]
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:427) ~[portmapper-master-2.0.0-alpha2.jar:na]
	at javax.swing.SwingWorker$1.call(Unknown Source) ~[na:1.7.0_79]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.7.0_79]
	at javax.swing.SwingWorker.run(Unknown Source) ~[na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.7.0_79]
	at java.lang.Thread.run(Unknown Source) ~[na:1.7.0_79]
WARN  Could not connect to router: Did not find a router

**Comment by JohnReedLOL** [comment]
DEBUG Open Settings dialog
DEBUG Create settings dialog
DEBUG Use entity encoding is true
DEBUG Saved settings [Settings: presets=[Dummy], useEntityEncoding=true, logLevel=ALL, routerFactoryClassName=org.chris.portmapper.router.weupnp.WeUPnPRouterFactory]
TRACE Connecting to router...
INFO  Creating router factory for class org.chris.portmapper.router.weupnp.WeUPnPRouterFactory
DEBUG Creating a new instance of the router factory class class org.chris.portmapper.router.weupnp.WeUPnPRouterFactory
DEBUG Router factory created
INFO  Searching for routers...
DEBUG System property portmapper.locationUrl not defined: discover routers automatically.
DEBUG Searching for gateway devices...
TRACE Current element 'major' has value '1'
TRACE Current element 'minor' has value '0'
TRACE Current element 'deviceType' has value 'urn:schemas-upnp-org:device:InternetGatewayDevice:1'
TRACE Current element 'friendlyName' has value 'TEW-711BR'
TRACE Current element 'manufacturer' has value 'Trendnet'
TRACE Current element 'manufacturerURL' has value 'http://www.trendnet.com'
TRACE Current element 'modelDescription' has value 'Trendnet 711 router'
TRACE Current element 'modelName' has value 'Trendnet router'
TRACE Current element 'modelNumber' has value 'TEW-711BR'
TRACE Current element 'modelURL' has value 'http://www.trendnet.com'
TRACE Current element 'UDN' has value 'uuid:12342409-1234-1234-5678-ee1234cc5678'
TRACE Current element 'serviceType' has value 'urn:schemas-dummy-com:service:Dummy:1'
TRACE Current element 'serviceId' has value 'urn:dummy-com:serviceId:dummy1'
TRACE Current element 'controlURL' has value '/dummy'
TRACE Current element 'eventSubURL' has value '/dummy'
TRACE Current element 'SCPDURL' has value '/dummy.xml'
TRACE Current element 'deviceType' has value 'urn:schemas-upnp-org:device:WANDevice:1'
TRACE Current element 'friendlyName' has value 'WANDevice'
TRACE Current element 'manufacturer' has value 'miniupnp'
TRACE Current element 'manufacturerURL' has value 'http://www.trendnet.com'
TRACE Current element 'modelDescription' has value 'WAN Device'
TRACE Current element 'modelName' has value 'WAN Device'
TRACE Current element 'modelNumber' has value '1'
TRACE Current element 'modelURL' has value 'http://www.trendnet.com'
TRACE Current element 'serialNumber' has value '00000000'
TRACE Current element 'UDN' has value 'uuid:12342409-1234-1234-5678-ee1234cc5678'
TRACE Current element 'UPC' has value 'MINIUPNPD'
TRACE Current element 'serviceType' has value 'urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1'
TRACE Current element 'serviceId' has value 'urn:upnp-org:serviceId:WANCommonIFC1'
TRACE Current element 'controlURL' has value '/upnp/control/WANCommonInterfaceConfig'
TRACE Current element 'eventSubURL' has value '/upnp/event/WANCommonInterfaceConfig'
TRACE Current element 'SCPDURL' has value '/wancfg.xml'
TRACE Current element 'deviceType' has value 'urn:schemas-upnp-org:device:WANConnectionDevice:1'
TRACE Current element 'friendlyName' has value 'WANConnectionDevice'
TRACE Current element 'manufacturer' has value 'miniupnp'
TRACE Current element 'manufacturerURL' has value 'http://www.trendnet.com'
TRACE Current element 'modelDescription' has value 'miniupnp daemon'
TRACE Current element 'modelName' has value 'miniupnpd'
TRACE Current element 'modelNumber' has value '1'
TRACE Current element 'modelURL' has value 'http://www.trendnet.com'
TRACE Current element 'serialNumber' has value '00000000'
TRACE Current element 'UDN' has value 'uuid:12342409-1234-1234-5678-ee1234cc5678'
TRACE Current element 'UPC' has value 'MINIUPNPD'
TRACE Current element 'serviceType' has value 'urn:schemas-upnp-org:service:WANIPConnection:1'
TRACE Current element 'serviceId' has value 'urn:upnp-org:serviceId:WANIPConn1'
TRACE Current element 'controlURL' has value '/upnp/control/WANIPConnection'
TRACE Current element 'eventSubURL' has value '/upnp/event/WANIPConnection'
TRACE Current element 'SCPDURL' has value '/wanipcn.xml'
TRACE Current element 'presentationURL' has value 'http://192.168.10.1/'
INFO  Connected to router TEW-711BR
TRACE Updating addresses...
TRACE Updating port mappings...
DEBUG Getting port mapping 0...
DEBUG Got an exception with message 'Got error code '713' when getting port mapping 0' for index 0, stop getting more mappings
DEBUG Found 1 devices
DEBUG Got null port mapping for index 0
DEBUG Device (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:12342409-1234-1234-5678-ee1234cc5678, Descriptor: http://192.168.10.1:52869/picsdesc.xml, Root: false supports ip service type: (RemoteService) Descriptor: /wanipcn.xml
INFO  Found 0 mappings
DEBUG Found connection service (RemoteService) Descriptor: /wanipcn.xml
TRACE done
DEBUG Found 1 devices
DEBUG Device (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:12342409-1234-1234-5678-ee1234cc5678, Descriptor: http://192.168.10.1:52869/picsdesc.xml, Root: false supports ip service type: (RemoteService) Descriptor: /wanipcn.xml
DEBUG Found connection service (RemoteService) Descriptor: /wanipcn.xml
DEBUG Connection state changed to true

**Comment by kaklakariada** [comment]
Sorry for the long delay. The second log looks like connection with weupnp was successful. Did this solve your problem?
