### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by HappyOni** [kaklakariada/portmapper#61]
I get this response when using the port mapping preset i made

INFO  2 port mapping added successfully
ERROR Invocation (ActionInvocation) (Action, Arguments: 9) GetGenericPortMappingEntry failed with operation '500 Internal Server Error', body '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>713</errorCode><errorDescription>SpecifiedArrayIndexInvalid</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>'
INFO  Got error response when fetching port mapping for entry number 2: '(IncomingActionResponseMessage) 500 Internal Server Error'. Stop getting more entries.
INFO  Found 2 mappings
INFO  Found service of wrong type urn:schemas-upnp-org:device:MediaServer:1, expected urn:schemas-upnp-org:device:InternetGatewayDevice:1.
INFO  Found service of wrong type urn:schemas-wifialliance-org:device:WFADevice:1, expected urn:schemas-upnp-org:device:InternetGatewayDevice:1.

Is this normal?

**Comment by kaklakariada** [comment]
Yes, this is normal. You can find an explanation here: https://github.com/kaklakariada/portmapper#error-when-fetching-port-mappings
