### ISSUE TITLE
portmapper failing to find mappings

### ISSUE THREAD

**Issue by zRodrigoGaspar** [kaklakariada/portmapper#62]
hi,
i've been using portmapper for 25565 ports, and it's been working fine.
since yesterday it started not finding mappings randomly and its never working.
here's the issue log:

WARN  unspecified resource Application.vendorId using UnknownApplicationVendor
INFO  Using default configuration directory 'C:\Users\Rodrigo Gaspar\AppData\Roaming\UnknownApplicationVendor\PortMapper'.
DEBUG Loading settings from file settings.xml
DEBUG Got settings [Settings: presets=[ewfwe, gfdgdfg, 45646456fd], useEntityEncoding=true, logLevel=INFO, routerFactoryClassName=org.chris.portmapper.router.cling.ClingRouterFactory]
INFO  Creating router factory for class org.chris.portmapper.router.cling.ClingRouterFactory
INFO  Searching for routers...
INFO  >>> Starting UPnP service...
INFO  Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
INFO  Creating Router: org.fourthline.cling.transport.RouterImpl
INFO  Creating wildcard socket (for receiving multicast datagrams) on port: 1900
INFO  Joining multicast group: /239.255.255.250:1900 on network interface: Realtek PCIe GbE Family Controller
INFO  Created server (for receiving TCP streams) on: /192.168.1.69:55248
INFO  Creating bound socket (for datagram input/output) on: /192.168.1.69
INFO  <<< UPnP service started successfully
INFO  Connected to router ' Vodafone HS8247W Gateway Huawei Model'
INFO  Got error response when fetching port mapping for entry number 0: '(IncomingActionResponseMessage) 500 Internal Server Error'. Stop getting more entries.
INFO  Found 0 mappings

what can i do?

**Comment by kaklakariada** [comment]
This could be caused by a firmware update of your router or modified settings. Check that UPnP is active in your router's configuration.

**Comment by kaklakariada** [comment]
Closing as stale.
