### ISSUE TITLE
Port presets automatically get unmapped after awhile

### ISSUE THREAD

**Issue by cintlex** [kaklakariada/portmapper#81]
Title explains, after a day or two of ports sitting it will automatically disconnect from my router and unmap the ports I selected, preventing anyone from coming in. Any way to fix this?

**Comment by kaklakariada** [comment]
Hi @cintlex,
thank you for your ticket!
Automatically unmapping ports is a feature of your router. To avoid this, you can run a script that regularly updates the mapping, see https://github.com/kaklakariada/portmapper#port-mappings-are-expiring for details.

**Comment by kaklakariada** [comment]
I will close this now. If you need further support, please re-open this issue.
