### ISSUE TITLE
Ports listed as opened yet actually not opened.

### ISSUE THREAD

**Issue by PicklePenger** [kaklakariada/portmapper#88]
I'm being driven up a wall with this one... I create a preset in PortMapper, change the internal client to what is found in CMD (I have to manually set it off Local Host because my motherboard's ethernet was fried by a lightning strike and I'm using a network adapter now), set the ports, and click on "Use." The ports show as listed in the port mappings table but when I use an open port check tool, the port is listed as closed... PLEASE help.
![image](https://user-images.githubusercontent.com/80995339/125371434-b8a97680-e34e-11eb-99b5-37213c9746ed.png)
![image](https://user-images.githubusercontent.com/80995339/125371507-e4c4f780-e34e-11eb-9c70-ae1ad90ac7c9.png)

INFO  2 port mapping added successfully
ERROR Invocation (ActionInvocation) (Action, Arguments: 9) GetGenericPortMappingEntry failed with operation '500 Internal Server Error', body '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>713</errorCode><errorDescription>SpecifiedArrayIndexInvalid</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>'
INFO  Got error response when fetching port mapping for entry number 2: '(IncomingActionResponseMessage) 500 Internal Server Error'. Stop getting more entries.
INFO  Found 2 mappings

I'm also seeing:
WARN  Skipping invalid service '(RemoteService) Descriptor: dial_SCPD.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:295c0017-2402-108e-80b4-acae1949f933, Descriptor: http:_[MY INTERNAL IP]_//0/dial/dd.xml, Root: true

**Comment by kaklakariada** [comment]
Hi @PicklePenger,
The error message when fetching port mappings (`GetGenericPortMappingEntry failed with operation '500 Internal Server Error'`) is a [known issue](https://github.com/kaklakariada/portmapper#error-when-fetching-port-mappings) and does not affect the port mappings.

Regarding the closed port: I am sorry but there is nothing I can do. This may be an issue with your router or your ISP. To diagnose the issue you could create the port mapping using your routers admin interface.

**Comment by PicklePenger** [comment]
Well, thank you nonetheless. Fortunately, I have fixed the issue. The port came back as closed when utilizing one of those open port check tools because I had yet to actually run the and there was nothing to respond to the website checking the port's status. An oversight on my behalf.

Everything works great now and thank you for both the tool and your help.

**Comment by kaklakariada** [comment]
Thank you for your feedback!

I added a [section](https://github.com/kaklakariada/portmapper/blob/master/README.md#ports-are-not-forwarded) to the troubleshooting guide with your solution.
