### ISSUE TITLE
FlatLaf?

### ISSUE THREAD

**Issue by b0vik** [kaklakariada/portmapper#96]

**Comment by kaklakariada** [comment]
@asolidtime What do you mean with "FlatLaf"?

**Comment by asolidtime** [comment]
Sorry, that was a bit cryptic of me. What I meant was that (imo) the app's default theme looks kind of ugly, and I was suggesting that you use [a Swing theme library like FlatLaf](https://www.formdev.com/flatlaf/) for a default theme.  
Here's your app using the default theme on my device:
![Screenshot_20220226_155247](https://user-images.githubusercontent.com/75963592/155860306-0f9f1fd2-4f4f-4e0e-81d3-9e5745eaa334.png)
And here's FlatLaf Dark:
![Screenshot_20220226_155509](https://user-images.githubusercontent.com/75963592/155860353-cf15f658-981c-4032-bfa3-02c1f8abafd5.png)
and Light:
![Screenshot_20220226_155618](https://user-images.githubusercontent.com/75963592/155860382-5be47133-fc40-4c5d-824a-c1fe8fa172ee.png)
It's totally not something you need to do (or an issue with this app) but it does look a bit cooler.

**Comment by brunoais** [comment]
Flatleaf looks.... Flat. It's way harder to know what things are buttons and what aren't. I prefer the slight skeuomorph of the current theme.

**Comment by kaklakariada** [comment]
Good point. I also would like to keep the number of dependencies as low as possible.
