### ISSUE TITLE
Can't open portmapper

### ISSUE THREAD

**Issue by A7mad3109v2** [kaklakariada/portmapper#98]
I cant open portmapper for some reason
I tried double clicking or using java -jar portmapper-2.2.1 in command prompt but it does not work?

**Comment by kaklakariada** [comment]
@A7mad3109v2  A possible reason is that your java version is too old. Please use Java 11 or later. If this doesn't help, please send the command line output of the error.

**Comment by kaklakariada** [comment]
Closing as stale.
